### PR TITLE
Ef7 beta7 basics

### PR DESCRIPTION
**Pull request by CezarCretu**

### CODE REVIEW

**Comment by borgdylan** [comment]
Why would you delete the project.json files? Without them no one will be able to build the code!

**Comment by roji** [comment]
@borgdylan, we temporarily removed the project.json because VS with Nuget 3.1 has some severe issues with projects that have both systems (csproj and project.json in parallel). But it's entirely possible to build EF7 with csproj, so I thought of deferring the project.json/DNX work until it's more stable and necessary for CorrCLR. Do you see an issue with that?

**Comment by roji** [comment]
@CezarCretu: am traveling, will review this soon!

**Comment by borgdylan** [comment]
I see no issue as long as I do not have to build it myself while trying EF7 stuff.

**Comment by roji** [comment]
@borgdylan, sorry, do you mean the csproj-based build isn't working for you somehow for the EF7 provider?

**Pull request merged**
